//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositPayment
    {
        public int ID { get; set; }
        public string TransactionCode { get; set; }
        public string Currency { get; set; }
        public string DepositAmount { get; set; }
        public string Reference { get; set; }
        public string Supplement { get; set; }
        public string CreditCard { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> ReservationType { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
